#!/bin/bash
clear 
#color
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;32m'
NC='\033[0m'

#read -p "you need change hostname: " NAM
#sudo hostnamectl set-hostname $NAM
#check package installed...
echo "+===================+"
echo -e "|$BLUE Install package. $NC |"
echo "+===================+"
for P in $(cat /opt/pionux/koompi-enterprise-client/package/package_x86_64)
do
    if [[ -n "$(pacman -Q $P)" ]];then 
        echo -e "Package: $RED $P $NC Installed."
    else 
        sudo pacman -S $P --noconfirm
        echo -e "Package: $RED $P $NC Installed successful."
    fi
done

read -p "Domain: " VAL1
read -p "IP Address: " IPADDRESS

newdomains=$VAL1
NEWDOMAIN=$(echo "$VAL1" | tr '[:lower:]' '[:upper:]')
newsubdomains=$(echo "$VAL1" | awk -F'.' '{print $1}')
NEWSUBDOMAIN=$(echo "$newsubdomains" | tr '[:lower:]' '[:upper:]')

#krb5 rename
echo "configuring krb5..."
grep -rli DOMAIN /opt/pionux/koompi-enterprise-client/krb5/* | xargs -i@ sed -i s/DOMAIN/$NEWDOMAIN/g @
grep -rli domains /opt/pionux/koompi-enterprise-client/krb5/* | xargs -i@ sed -i s/domains/$newdomains/g @
grep -rli subdomain /opt/pionux/koompi-enterprise-client/krb5/* | xargs -i@ sed -i s/subdomain/$newsubdomains/g @
sudo cp /etc/krb5.conf /etc/krb5.conf.backup
sudo cp /opt/pionux/koompi-enterprise-client/krb5/krb5.conf /etc/krb5.conf

#samba rename
echo "configuring samba..."
grep -rli SUBDOMAIN /opt/pionux/koompi-enterprise-client/samba/smb.conf | xargs -i@ sed -i s/SUBDOMAIN/$NEWSUBDOMAIN/g @
grep -rli DOMAIN /opt/pionux/koompi-enterprise-client/samba/smb.conf | xargs -i@ sed -i s/DOMAIN/$NEWDOMAIN/g @
grep -rli domains /opt/pionux/koompi-enterprise-client/samba/smb.conf | xargs -i@ sed -i s/domains/$newdomains/g @
sudo cp /opt/pionux/koompi-enterprise-client/samba/smb.conf /etc/samba/smb.conf
sudo cp /opt/pionux/koompi-enterprise-client/samba/pam_winbind.conf /etc/security/pam_winbind.conf
grep -rli HOSTNAME /opt/pionux/koompi-enterprise-client/samba/smb.conf | xargs -i@ sed -i s/HOSTNAME/$(hostname)/g @

#client rename
echo "configuring client..."
grep -rli SUBDOMAIN /opt/pionux/koompi-enterprise-client/scripts/client | xargs -i@ sed -i s/SUBDOMAIN/$NEWSUBDOMAIN/g @
sudo cp /opt/pionux/koompi-enterprise-client/scripts/client /usr/bin/client
sudo cp /opt/pionux/koompi-enterprise-client/scripts/mysmb /usr/bin/mysmb
sudo cp /opt/pionux/koompi-enterprise-client/service/mysmb.service /usr/lib/systemd/system/
sudo chmod +x /usr/bin/mysmb

echo "configuring nsswitch..."
sudo cp /opt/pionux/koompi-enterprise-client/nsswitch/nsswitch.conf /etc/nsswitch.conf

echo "configuring pam.d..."
sudo cp /opt/pionux/koompi-enterprise-client/pam.d/* /etc/pam.d/

echo "configuring desktop..."
sudo cp /opt/pionux/koompi-enterprise-client/Desktop/pionuxicon.png /usr/share/pixmaps/
sudo cp /opt/pionux/koompi-enterprise-client/Desktop/Mount.desktop /usr/share/applications/
sudo cp /opt/pionux/koompi-enterprise-client/Desktop/Mount.desktop /etc/skel/.config/autostart

echo "configuring host..."
sudo cp /etc/hosts ./
sudo chown -R $(id -u -n):users ./hosts
echo "$IPADDRESS     $VAL1   $NEWSUBDOMAIN" >> ./hosts
sudo cp /opt/pionux/koompi-enterprise-client/client-setup/hosts /etc/hosts
sudo rm -rf /opt/pionux/koompi-enterprise-client/client-setup/hosts

sudo cp /etc/resolv.conf ./
sudo chown -R $(id -u -n):users ./resolv.conf
echo "nameserver $IPADDRESS" > ./resolv.conf
echo "search $VAL1" >> ./resolv.conf
sudo cp ./resolv.conf /etc/resolv.conf


echo "stoping service..."
sudo systemctl enable smb nmb winbind mysmb
sudo systemctl stop smb nmb winbind mysmb

echo "join domain!!"
#sudo net rpc join  -S $VAL1 -U Administrator
domain=$(echo $VAL1 | tr '[:lower:]' '[:upper:]')
kinit administrator@$domain
sudo net join -U Administrator@$domain -S $VAL1

# echo "reboot in 5sce..."
# sleep 5
# sudo reboot
